# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: D-Bus Broker Developers

version = 1

[[annotations]]
path = "test/integration/.fmf/version"
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileCopyrightText = "D-Bus Broker Developers"
