#!/bin/bash

set -e

rm -Rf "./ci-build"
mkdir "./ci-build"
cd "./ci-build"

${CHERRY_LIB_MESONSETUP} . "${CHERRY_LIB_SRCDIR}"
${CHERRY_LIB_NINJABUILD}
${CHERRY_LIB_MESONTEST}
# XXX: Valgrind and sd-bus / dbus-daemon does not work nicely. We should
#      probably write some suppression rules.
#(( ! CHERRY_LIB_VALGRIND )) || ${CHERRY_LIB_MESONTEST} "--wrapper=${CHERRY_LIB_VALGRINDWRAP}"
