#!/bin/bash

set -e

#
# force rebuild
rm -Rf "./cibuild"

#
# configure build-dir if not available
meson setup \
        "./cibuild" \
        --prefix /usr \
        --buildtype debugoptimized \
        --warnlevel 2

#
# build everything
ninja -C "./cibuild"

#
# run test-suite
( cd "./cibuild" && meson test )

#
# run again via valgrind
#
# XXX: This currently fails horribly since libsystemd and dbus-daemon
#      are not valgrind-safe. Figure something out...
( cd "./cibuild" ; meson test -t 128 --wrap="$MY_VALGRIND" || exit 0 )
